<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name></name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d9ca05ed-c541-41ce-8570-8e771bb2b15d</testSuiteGuid>
   
<testCaseLink>
      <guid>b318c996-749c-4048-b978-e914320fa083</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Preferences/Set_Preferences</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>af713b08-c38d-4add-9957-436fcc02a193</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>5,6,7,8,9,10,11</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForPreferences</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>af713b08-c38d-4add-9957-436fcc02a193</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>20e66ddf-642f-491a-b46e-0d3dc565bf8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af713b08-c38d-4add-9957-436fcc02a193</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>4611fa3d-9817-4318-9699-09323a3d16ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af713b08-c38d-4add-9957-436fcc02a193</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>preference</value>
         <variableId>8c467d1f-9c4c-493c-a375-d9145f840bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b6bb43-2854-4a87-80e8-e8a6cc55b8f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a94cf29-3aca-457a-8b05-cbec1a213170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003edf9a-5cd2-49e7-b7ef-cf2adf5857a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630400d7-1a60-442c-afcd-0566c0a50cbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fb4bcc-6ac6-46ae-b1f3-d80a3cca2ee6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
