<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobSubmission</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8cfdd852-3168-4a44-b608-f186cd887fe6</testSuiteGuid>
   <testCaseLink>
      <guid>9664a690-ae89-4da4-8d27-b6ed156961c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-3</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJS-Latest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AppName</value>
         <variableId>26fbd4fc-965f-401e-a5c4-6fb431cd201b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>InputFile</value>
         <variableId>e9d3b8c0-f5fe-46e9-a72e-1a22d9f59c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>518a544d-f5ac-448a-acfc-06b909661db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileArg</value>
         <variableId>e66844e3-6552-46e7-8030-77932e3be780</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mode</value>
         <variableId>ea501a92-5498-450d-afcd-13bfabb19fdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ToChange</value>
         <variableId>816d5f07-afb8-4c81-9dde-4af3c892b31c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ChangeValue</value>
         <variableId>ea3c8f43-9d3d-4606-b294-b1768dbf277b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f87c18b2-6403-4273-98ac-d2fdc486f2d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/Bookmark_JobSubmissionForm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342bf84f-d731-46b2-bc09-0598f54f2c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e957165-146e-463b-a224-778888e896fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98ebd070-a82f-4332-81d4-243dafc56d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0fd68ee-be16-489f-b4f8-96a8f6773260</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d176fffb-2637-4b0d-99e5-8010ae6b4d00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2842aeb2-3e3c-43da-8819-4c642e77beea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/ProcessWith_Optistruct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecebbc7d-c682-48a7-ae90-b89b965c63d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee159a2f-337e-4f8f-84d6-4c5206a6e4f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bb1d38-b7f1-4761-8678-46a35eed5c08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e58b199-7771-4196-ac0c-321816b8fb8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-NavigatingPreviousFolder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91eeea77-0135-448f-8089-ed42cb63d23d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49b64022-8afd-42b1-95c6-b05be9bece94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4159cb7-03c4-41d9-b199-73357b3822db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd968dd8-ccc8-4734-bfaa-6318ad834c85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>504c5d99-bd14-4b6d-a669-39e8734051a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47d7a593-f5b6-4045-a8fc-66fbc6454862</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileProcessWith-2020.4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f437cb72-d460-45b9-8457-506e053653fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41e4999d-53fd-4ac2-ac7d-b32dd14c947d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23a39b4b-3cb1-49da-b642-9ada0fa81727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a90f198e-6076-4a17-8e68-6f8a2df56aff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061b16b1-00b0-4549-9442-8ba2fd0e9bdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>717d5e86-3349-4836-8c36-9a645d19d409</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7da3dbe-cda1-4760-8151-ce2be493bf2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission -NumericUser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2c707b8-53df-4928-86a3-637f663a971f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b8933d-6cd2-4a85-8de5-01c2365f0d2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c93ccba-46b0-4f74-885a-7849fe7f4096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d203727-e1e2-480e-8bfa-2b07adf0b11d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc5632f2-78f7-4983-baab-b7fa9882d17b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ecc7cb5-df43-4740-8c08-9d8e38cf6b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c6e5540-3a14-492f-a529-8d1d96af52dd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
