<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JSFileOps</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bf19985f-d238-4709-9542-973ba388574b</testSuiteGuid>
   <testCaseLink>
      <guid>7c2060f4-e812-439e-b73a-bf7da80ede90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60fc8295-97d4-4e81-a11c-c1bf7c1ef1be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6cca387c-ae79-43df-af08-1d94db925586</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-12</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0acca874-3122-46ab-a72c-14d70712430b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>883adf85-4cf5-4f4f-88d8-f75382095594</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>883adf85-4cf5-4f4f-88d8-f75382095594</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>883adf85-4cf5-4f4f-88d8-f75382095594</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>883adf85-4cf5-4f4f-88d8-f75382095594</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d76089aa-cb23-4d66-bb08-bfbe44cc6cd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FolderOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c166dacf-f745-4dfb-abe6-ed17c8037188</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFolderOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c166dacf-f745-4dfb-abe6-ed17c8037188</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>8105a991-43b5-43b0-8b1f-ee3f69e92345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4f6178-1b28-43aa-933b-1eb3ee68a864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c166dacf-f745-4dfb-abe6-ed17c8037188</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>1ce8f2e1-64d6-42e2-8daa-c642b7eaca9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c166dacf-f745-4dfb-abe6-ed17c8037188</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>0025ea3f-58a9-4de0-8d6b-0a01c78a12ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eaf3c1-c83b-40c5-9ffe-02caf94b28a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b74b1fa-6dbf-413f-8468-178521363c75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FolderOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7f8d3a11-6873-4cc1-89ce-d12ded8f768b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFolderOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7f8d3a11-6873-4cc1-89ce-d12ded8f768b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>8105a991-43b5-43b0-8b1f-ee3f69e92345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4f6178-1b28-43aa-933b-1eb3ee68a864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f8d3a11-6873-4cc1-89ce-d12ded8f768b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>1ce8f2e1-64d6-42e2-8daa-c642b7eaca9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f8d3a11-6873-4cc1-89ce-d12ded8f768b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>0025ea3f-58a9-4de0-8d6b-0a01c78a12ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eaf3c1-c83b-40c5-9ffe-02caf94b28a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d6c6aa3-018c-49b5-b1e7-c4d15b7453ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4dc4abda-ffae-474b-8b30-657098409991</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Helpbox_Disabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5db5f97f-7c3f-46a5-9413-2c85d232247c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688e3f36-1d89-4e42-bfad-be5a3bb54374</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190ae24b-12f7-4578-8d71-8a6b73beed19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acaa2c69-65ab-4e96-8c8e-c2bb86950a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb41cccf-9ba4-425d-a4a3-ed2e62fd39ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b466ff-5064-4ec3-9e88-d5498d7717cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c954eee0-071d-4262-a7d7-edc6f53162c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d0fe48d-3f8c-4a6f-98cc-2edaa8da6a72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0452b09a-2c08-4d5c-ba11-b1abde3ea862</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>11-12</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0452b09a-2c08-4d5c-ba11-b1abde3ea862</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0452b09a-2c08-4d5c-ba11-b1abde3ea862</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51d4bc8d-b456-424c-b30b-296ed2fc4553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-switchApplication</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5fc2ade-2b0d-4f8c-9c81-250fff92cae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6413bb5-8219-4755-a651-79cc0c9b129f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d136fd6a-f3fa-44c6-bfda-d4211751b61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11230f5d-2647-4379-8eb7-5ddb6672c072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50dac30-7a76-48be-b01d-426bbf80bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622ae497-c74e-472f-972d-2996e7120e60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22fde961-5a7d-4c8d-acf8-8ec4b585ad13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Helpbox_Enabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>680b0924-9886-4c40-b374-1867e98cdce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4154522b-93ea-42f6-b3a5-f0ce4a87c87e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826fc129-a48b-47db-a772-1cdac51e73fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae327a85-f5a3-46a6-bbed-025090fd2145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe4b64c5-adf4-4325-b4d2-2572b9ccea22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edd19741-461c-4e09-9a05-854c2ccc88ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc671ec7-8c19-4a0b-a271-9357bb172c2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7df1ab6-fd52-45c5-821c-74d6d2b61609</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_LeaveForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e3fa02d-095a-446d-81a7-a728e667e5fd</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4e3fa02d-095a-446d-81a7-a728e667e5fd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eafa6e12-0135-42fc-b1ff-a3f118a8a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7719920b-c14d-43fe-a629-bcb6b8101040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e3fa02d-095a-446d-81a7-a728e667e5fd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>005889aa-cf57-4be6-a956-bb131f6725ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8aaa38b-e7ab-4eed-b1df-7c087e7bd6bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d464ced-a2a4-4303-a295-d4ba9e350b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d26efc6-8c56-4d38-95d0-4527217d2a44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobFiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea55ab9f-206e-4fcf-9ae0-7848cbada80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea661e7b-c276-42ef-a6c9-1c1ef53f2265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d599e9-d250-4bbc-8dc9-b8509e150c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd0c7cf-20ad-4071-a100-4a42f1e373db</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
